version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend
  ui:
    image: ${D_USERNAME}/ui:${UI_TAG}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - frontend
  post:
    image: ${D_USERNAME}/post:${POST_TAG}
    environment:
    - POST_DATABASE_HOST=mongo_db
    networks:
      - frontend
      - backend
  comment:
    image: ${D_USERNAME}/comment:${COMMENT_TAG}
    environment:
    - COMMENT_DATABASE_HOST=mongo_db
    networks:
      - frontend
      - backend
  prometheus:
    image: ${D_USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - frontend
      - backend

volumes:
  post_db:
  prometheus_data:

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
