{
 "title": "Docker Engine Metrics Telegraf",
 "tags": [
  "docker",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "cpu_usage_percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Total Network Actions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes[$__interval])",
     "legendFormat": "{{com_docker_compose_service}}"
    },
    {
     "expr": "-rate(docker_container_net_tx_bytes[$__interval])",
     "legendFormat": "{{com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "mem_usage_percent",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent",
     "legendFormat": "{{com_docker_compose_service}}"
    }
   ]
  }
 ]
}